# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiddenforum', '0002_hiddenpost_hiddenforum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenpost',
            name='hiddenforum',
            field=models.CharField(max_length=120),
        ),
    ]
